import type { Locale } from "@/lib/i18n";

export function getUiCopy(locale: Locale) {
  if (locale === "vi") {
    return {
      ctaProjects: "Xem dự án",
      ctaContact: "Liên hệ",
      ctaBlog: "Đọc bài viết",
      ctaResume: "Xem hồ sơ",
      selectedProjects: "Dự án chọn lọc",
      latestWriting: "Bài viết mới",
      allProjects: "Tất cả dự án",
      allWriting: "Tất cả bài viết",
      whyThisSite: "Cách portfolio này được cấu trúc",
      projectIndexEyebrow: "Case studies",
      blogIndexEyebrow: "Writing",
      aboutEyebrow: "Background",
      resumeEyebrow: "Summary",
      contactEyebrow: "Contact",
      homeEyebrow: "Senior / Lead Developer",
      proofProjects: "Projects",
      proofWriting: "Writing",
      proofLocale: "Locale",
      proofFocus: "Focus",
      labelRole: "Vai trò",
      labelLocation: "Địa điểm",
      labelPeriod: "Thời gian",
      labelTeam: "Nhóm",
      labelEmail: "Email",
      labelReadTime: "Thời gian đọc",
      labelLiveDemo: "Bản chạy thử",
      labelSource: "Mã nguồn",
      labelFeaturedProjectsCount: "case study nổi bật",
      labelPublishedEntriesCount: "bài viết đã xuất bản",
      filterAll: "Tất cả",
      filterLabel: "Lọc theo tag",
      noMatches: "Chưa có nội dung khớp với tag này.",
      articleFallback: "Bài viết này hiện mới có bản tiếng Anh.",
      projectFallback: "Case study này hiện mới có bản tiếng Anh.",
      publishedOn: "Xuất bản",
      updatedOn: "Cập nhật",
      stack: "Stack",
      results: "Kết quả",
      readNext: "Đọc tiếp",
      backToProjects: "Quay lại dự án",
      backToBlog: "Quay lại bài viết",
      connectTitle: "Nếu thấy hướng làm việc này phù hợp, hãy liên hệ trực tiếp.",
      connectSummary:
        "Tôi ưu tiên các vai trò senior IC, lead hoặc collaboration cần người vừa triển khai vừa giữ chất lượng kiến trúc.",
      contactFormTitle: "Gửi lời nhắn nhanh",
      contactFormSummary:
        "Form này đi thẳng vào inbox khi env production đã được cấu hình. Nếu chưa, hệ thống vẫn chấp nhận request an toàn để bạn tiếp tục test.",
      formName: "Tên",
      formEmail: "Email",
      formCompany: "Công ty",
      formSubject: "Tiêu đề",
      formMessage: "Nội dung",
      formSubmit: "Gửi",
      formSubmitting: "Đang gửi...",
      formSuccess: "Đã nhận yêu cầu. Tôi sẽ phản hồi sớm.",
      formSoftAccepted:
        "Yêu cầu đã được chấp nhận nhưng email production chưa được cấu hình đầy đủ.",
      formError: "Gửi thất bại. Kiểm tra lại thông tin rồi thử lại.",
      formTurnstileError: "Xác minh chống spam thất bại. Hãy thử lại.",
      homeSupportTitle: "Một portfolio nên cư xử như một sản phẩm, không phải một gallery.",
      homeSupportSummary:
        "Mỗi phần ở đây được tối ưu để recruiter hoặc hiring manager nắm được vai trò, phạm vi công việc, cách ra quyết định và độ tin cậy kỹ thuật trong vài phút đầu.",
    };
  }

  return {
    ctaProjects: "View projects",
    ctaContact: "Contact",
    ctaBlog: "Read writing",
    ctaResume: "View resume",
    selectedProjects: "Selected projects",
    latestWriting: "Latest writing",
    allProjects: "All projects",
    allWriting: "All writing",
    whyThisSite: "How this portfolio is structured",
    projectIndexEyebrow: "Case studies",
    blogIndexEyebrow: "Writing",
    aboutEyebrow: "Background",
    resumeEyebrow: "Summary",
    contactEyebrow: "Contact",
    homeEyebrow: "Senior / Lead Developer",
    proofProjects: "Projects",
    proofWriting: "Writing",
    proofLocale: "Locale",
    proofFocus: "Focus",
    labelRole: "Role",
    labelLocation: "Location",
    labelPeriod: "Period",
    labelTeam: "Team",
    labelEmail: "Email",
    labelReadTime: "Read time",
    labelLiveDemo: "Live demo",
    labelSource: "Source",
    labelFeaturedProjectsCount: "featured case studies",
    labelPublishedEntriesCount: "published entries",
    filterAll: "All",
    filterLabel: "Filter by tag",
    noMatches: "No entries match this tag yet.",
    articleFallback: "This entry is currently available in English only.",
    projectFallback: "This case study is currently available in English only.",
    publishedOn: "Published",
    updatedOn: "Updated",
    stack: "Stack",
    results: "Results",
    readNext: "Continue reading",
    backToProjects: "Back to projects",
    backToBlog: "Back to blog",
    connectTitle: "If this working style fits, reach out directly.",
    connectSummary:
      "I am most useful in senior IC, lead, or collaboration roles where implementation quality and architecture both matter.",
    contactFormTitle: "Send a direct note",
    contactFormSummary:
      "This form routes to a real inbox once production env is configured. Until then, it still accepts requests safely for end-to-end testing.",
    formName: "Name",
    formEmail: "Email",
    formCompany: "Company",
    formSubject: "Subject",
    formMessage: "Message",
    formSubmit: "Send message",
    formSubmitting: "Sending...",
    formSuccess: "Message accepted. I will get back to you soon.",
    formSoftAccepted:
      "Request accepted, but production email delivery has not been configured yet.",
    formError: "Submission failed. Check the details and try again.",
    formTurnstileError: "Spam verification failed. Please try again.",
    homeSupportTitle: "A portfolio should behave like a product, not a gallery.",
    homeSupportSummary:
      "Every section here is tuned so a recruiter or hiring manager can understand role, scope, decision quality, and technical credibility within the first few minutes.",
  };
}
